name: Docker build

on:
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.3.268.0
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        destination: ${{ github.workspace }}/vulkan-sdt

    - name: Build Docker image
      run: docker build -t lods --build-arg VULKAN_DLL_PATH=./vulkan-sdt/1.3.268.0/runtime/x64/vulkan-1.dll .

    - name: Execute test case | tmp
      run: |
        docker run -d -e HTTP_SERVER_PORT=8080 -e HTTP_SERVER_HOST=0.0.0.0 lods > container_id.txt
        sleep 180
        docker logs $(cat container_id.txt)