name: CI/CD on main branch

on:
  push:
    branches:
      - main

jobs:
  quay-build-push:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Mark published image as next
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          docker pull quay.io/decentraland/lods-generator:${COMMIT_HASH}
          docker tag quay.io/decentraland/lods-generator:${COMMIT_HASH} quay.io/decentraland/lods-generator:next
          docker push quay.io/decentraland/lods-generator:next