name: Manual deployment

on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        required: true
        type: choice
        options:
          - prd
          - dev
        default: prd
        description: Environment
      tag:
        required: true
        default: "latest"
        type: string
        description: "Docker tag (quay.io)"

jobs:
  deployment:
    if: ${{ inputs.deployment-environment }}
    name: "Deploy to: ${{ inputs.deployment-environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }}
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "quay.io/decentraland/lods-generator:${{ inputs.tag }}"
          serviceName: "lods-generator"
          env: ${{ inputs.deployment-environment }}
          token: ${{ secrets.GITHUB_TOKEN }}