name: CI/CD on Releases

on:
  release:
    types: [published]

jobs:
  quay-build-push:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Mark published image as latest
        run: |
          docker pull quay.io/decentraland/lods-generator:next
          docker tag quay.io/decentraland/lods-generator:next quay.io/decentraland/lods-generator:latest
          docker push quay.io/decentraland/lods-generator:latest
