name: Build LOD

on:
  workflow_dispatch:
    inputs:
      sceneType:
        description: 'Hash or coords'
        required: true
        default: 'coords'
      sceneDescription:
        description: 'Scene description'
        required: true
        default: '-129,-77'
      decimationRatio:
        description: 'Decimation Ratio'
        required: true
        default: '50'

jobs:
  build-and-run:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Publish with dotnet
      run:  dotnet publish -c Release -r win10-x64 -o ./publish --self-contained true 

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.3.268.0
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        destination: ${{ github.workspace }}/vulkan-sdt

    - name: Move Vulkan DLL to output directory
      run: |
        mv ./vulkan-sdt/1.3.268.0/runtime/x64/vulkan-1.dll ./publish/
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.14.2'

    - name: Run the application
      run: .\publish\DCL_PiXYZ.exe "${{ github.event.inputs.sceneType }}" "${{ github.event.inputs.sceneDescription }}" "${{ github.event.inputs.decimationRatio }}" "scene-lod-entities-manifest-builder/" "OutputDirectoryPath/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output-artifacts
        path: OutputDirectoryPath/